<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
        <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.17" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\ShopFlow.ProductService\ShopFlow.ProductService.csproj" />
        <ProjectReference Include="..\src\ShopFlow.Contracts\ShopFlow.Contracts.csproj" />
        <ProjectReference Include="..\src\ShopFlow.Common\ShopFlow.Common.csproj" />
    </ItemGroup>

</Project>